# Generated by Django 2.0 on 2018-07-07 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('object_id', models.PositiveIntegerField(verbose_name='博客ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='博客分类')),
            ],
            options={
                'verbose_name': '阅读数据',
                'verbose_name_plural': '阅读数据',
            },
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
        migrations.AlterField(
            model_name='readnum',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
