# Generated by Django 2.0 on 2018-06-29 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '阅读数据', 'verbose_name_plural': '阅读数据'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType', verbose_name='博客分类'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='博客ID'),
        ),
    ]
