"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jx2e++rujkj)_t%80u33k3hobo7r6=@-nh0rmhkl!_$c6kik@g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'blog',
    'read_statistics',
    'comment',
    'likes',
    'user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.login_modal_form',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


#############################################################################


# 配置ckeditor
CKEDITOR_UPLOAD_PATH = 'upload/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar':(
            ['div', 'Source', '-', 'Save', 'NewPage', 'Preview', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-','Print','SpellChecker','Scayt'],
            ['Undo', 'Redo', '-', 'Find', 'Replace', '-', 'SelectAll', 'RemoveFormat','-','Maximize', 'ShowBlocks', '-',"CodeSnippet", 'Subscript', 'Superscript'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton','HiddenField'],
            ['Bold', 'Italic', 'Underline', 'Strike', '-'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ),
        'extraPlugins': 'codesnippet',

    'smiley_images':[
        '1 (1).png','1 (2).png','1 (4).png','1 (5).png','1 (6).png','1 (7).png','1 (8).png','1 (9).png','1 (10).png',
        '1 (11).png','1 (12).png','1 (13).png','1 (14).png','1 (15).png','1 (16).png','1 (17).png','1 (19).png','1 (20).png',
        '1 (21).png','1 (22).png','1 (24).png','1 (26).png','1 (27).png','1 (28).png','1 (29).png','1 (30).png',
        '1 (31).png','1 (32).png','1 (33).png','1 (34).png','1 (35).png','1 (36).png','1 (37).png','1 (38).png','1 (39).png','1 (40).png',
        '1 (41).png','1 (42).png','1 (43).png','1 (44).png','1 (45).png','1 (46).png','1 (48).png','1 (49).png','1 (50).png',
        '1 (51).png','1 (52).png','1 (53).png','1 (54).png','1 (55).png','1 (56).png','1 (57).png','1 (58).png','1 (59).png','1 (60).png',
        '1 (61).png','1 (62).png','1 (63).png','1 (64).png','1 (65).png','1 (66).png','1 (67).png','1 (68).png','1 (69).png','1 (70).png',
        '1 (71).png','1 (72).png','1 (73).png','1 (74).png','1 (75).png','1 (76).png','1 (77).png','1 (78).png',
    ],  #使用哪些表情

        'smiley_columns':10,  #控制行表情个数
        'smiley_descriptions':[],  #提示文字
    },


    'comment_ckeditor':{
        'toolbar':'custom',
        'toolbar_custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ["TextColor", "BGColor", 'RemoveFormat'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ["Smiley", "SpecialChar", 'Blockquote'],
        ],

    'smiley_images':[
        '1 (1).png','1 (2).png','1 (4).png','1 (5).png','1 (6).png','1 (7).png','1 (8).png','1 (9).png','1 (10).png',
        '1 (11).png','1 (12).png','1 (13).png','1 (14).png','1 (15).png','1 (16).png','1 (17).png','1 (19).png','1 (20).png',
        '1 (21).png','1 (22).png','1 (24).png','1 (26).png','1 (27).png','1 (28).png','1 (29).png','1 (30).png',
        '1 (31).png','1 (32).png','1 (33).png','1 (34).png','1 (35).png','1 (36).png','1 (37).png','1 (38).png','1 (39).png','1 (40).png',
        '1 (41).png','1 (42).png','1 (43).png','1 (44).png','1 (45).png','1 (46).png','1 (48).png','1 (49).png','1 (50).png',
        '1 (51).png','1 (52).png','1 (53).png','1 (54).png','1 (55).png','1 (56).png','1 (57).png','1 (58).png','1 (59).png','1 (60).png',
        '1 (61).png','1 (62).png','1 (63).png','1 (64).png','1 (65).png','1 (66).png','1 (67).png','1 (68).png','1 (69).png','1 (70).png',
        '1 (71).png','1 (72).png','1 (73).png','1 (74).png','1 (75).png','1 (76).png','1 (77).png','1 (78).png',
    ],  #使用哪些表情

        'smiley_columns':10,  #控制行表情个数
        'smiley_descriptions':[],  #提示文字

        'width': 'auto',
        'height': '200',
        'tabSpaces': 4,
        'removePlugins': 'elementspath',
        'resize_enabled': False,
    }
}


#############################################################################

# jet配置
JET_THEMES = [
    {
        'theme': 'default',
        'color': '#47bac1',
        'title': 'Default' 
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

# jet编辑器设置
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'airMode': False,
    'styleWithSpan': False,
    'width': '80%',
    'height': '480',
    'lang': 'zh-CN',
}

# jet 菜单设置
JET_SIDE_MENU_COMPACT = True

JET_INDEX_DASHBOARD  =  'jet.dashboard.dashboard.DefaultIndexDashboard'

#############################################################################


# haystack相关配置
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    }
}

HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
# 添加此项，当数据库改变时，会自动更新索引，非常方便
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

#############################################################################


# 每页博客展示条数
EACH_PAGE_BLOGS_NUMBER = 7


# 博客缓存设置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}


# 图片上传存放位置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
