# Generated by Django 2.0.3 on 2018-06-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180612_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
    ]
